---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr, filter, lag)
library(dplyr)

```

```{r}
data <- read_csv("data/util_data.csv")
```

```{r}
count(data, vars = InstanceType)
```

```{r}
data <- data %>% 
  dplyr::mutate(capacidade = dplyr::case_when(InstanceType == "t2.medium" ~ 2,
                                            InstanceType == "t2.micro" ~ 1,
                                            InstanceType == "c5.large" ~ 2,
                                            InstanceType == "c5.xlarge" ~ 4,
                                            InstanceType == "m5d.large" ~ 2,
                                            InstanceType == "m5d.xlarge" ~ 4,
                                            InstanceType == "r5.2xlarge" ~ 8,
                                            InstanceType == "t3.micro" ~ 2
                                           ))
```



```{r}
count(data, vars = capacidade)
```
```{r}
data1 <- data %>%
    dplyr::mutate(utilizacao = Average/capacidade)
```

```{r}
#limite_inferior = seq(39, 42)
#limite_superior = seq(60, 63)
```





