---
title: "Cron simulation analysis"
output:
  html_document:
    df_print: paged
---

As mentioned in previous reports, our team started questioning how essential it was for promotions and logistics applications to use cron configurations for their settings of minimum capacity. This analysis is our first look at a simulation made with version rnbwp-env249-stable of promotions-api.

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
```

```{r message=FALSE, warning=FALSE}
with_cron <- read_csv("output_with_cron.csv")
without_cron <- read_csv("output_without_cron.csv")
```
```{r}
comparison <- data.frame(with_cron$timestamp, with_cron$RealAllocatedCores, with_cron$AllocatedCores, without_cron$AllocatedCores) 
comparison <- comparison %>% 
  rename(timestamp = with_cron.timestamp, real = with_cron.RealAllocatedCores, with_cron = with_cron.AllocatedCores, without_cron = without_cron.AllocatedCores) %>% 
  mutate(date = as.POSIXct(timestamp, origin = "1970-01-01"))
```

## May 12th

```{r}
comparison %>%
  filter(timestamp >= 1652313600 & timestamp < 1652400000) %>% 
  pivot_longer(c(real, with_cron, without_cron)) %>% 
  ggplot(aes(x = date, y = value, color = name)) +
  geom_line() +
  theme(legend.position = "bottom") +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%d\n%Hh")
```
```{r}
comparison %>% 
  filter(timestamp >= 1652313600 & timestamp < 1652400000) %>% 
  pivot_longer(c(real, with_cron)) %>% 
  ggplot(aes(x = date, y = value, color = name)) +
  geom_line() +
  theme(legend.position = "bottom") +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%d\n%Hh")
```

```{r}
comparison %>% 
  filter(timestamp >= 1652313600 & timestamp < 1652400000) %>% 
  pivot_longer(c(real, without_cron)) %>% 
  ggplot(aes(x = date, y = value, color = name)) +
  geom_line() +
  theme(legend.position = "bottom") +
  scale_x_datetime(date_breaks = "2 hours", date_labels = "%d\n%Hh")
```


